### ISSUE TITLE
End of the main

### ISSUE THREAD

**Issue by Norias1011** [thebrisly/42-Cursus-Piscine#2]
In the FDF project in the fdf.c file and the main function, there is nothing after the while(1). Can the rest of the main function can be pushed please?

**Comment by thebrisly** [comment]
Hello, thank you very much for your message. I'll have to go to school to check my FdF repo as it was done a while ago :-)

**Comment by thebrisly** [comment]
Need to check this issue

**Comment by Norias1011** [comment]
Hello, thank you, and thank you for your website with all the explanation, it is really well done and helpful!
